### ISSUE TITLE
Interop

### ISSUE THREAD

**Issue by Dimous** [RobertBorghese/Haxe-to-UnboundCPP#2]
Hello! Would you please demonstrate interop?
_I personally would like to see how to declare and pass c-style callbacks in haxe._

**Comment by RobertBorghese** [comment]
It okay if I reopen? While I did add an [Interop C++ case](https://github.com/RobertBorghese/Haxe-to-UnboundCPP/tree/main/test/unit_testing/tests/Interop_CPP), I still haven't added the ability to generate "extern C" or C-like function typedefs. This issue is a good reminder 😅
