### ISSUE TITLE
String split incorrect output

### ISSUE THREAD

**Issue by PXshadow** [RobertBorghese/Haxe-to-UnboundCPP#4]
```haxe
function main() {
    trace("hello".split(""));
    // Rnd.hx:2: []
    // Expected: Rnd.hx:2: [h,e,l,l,o]
}
```

**Comment by RobertBorghese** [comment]
Oooo! Nice catch, thanks!

**Comment by RobertBorghese** [comment]
[Fixed!](https://github.com/RobertBorghese/Haxe-to-UnboundCPP/commit/8ffdcaa3cf18801bc8eec845e0b25bd98dece1ce) What's weird is I even had a test already for this, but I had the correct thing set wrong. Think I got `"".split()` and `"something".split("")` confused.

Anyway, thanks again for the catch!
