### ISSUE TITLE
Compile Error: Log.hx:39

### ISSUE THREAD

**Issue by onehundredfeet** [RobertBorghese/Haxe-to-UnboundCPP#7]
Hi,

the Stdlib seems to cause a compile error:

```bash
/opt/homebrew/share/haxe/std/haxe/Log.hx:39: lines 39-40 : Dynamic not supported. Consider using Any or generics instead?
```

**Comment by onehundredfeet** [comment]
It's my trace.  Am I doing something wrong?

```haxe
        var v : Float2 = Float2.zero();
        var x :Float = v.x;
        var y :Float = v.y;
        trace('WHooo hooo! ${x} ${y}');
```

**Comment by RobertBorghese** [comment]
That should work... hmmmm... I'll see if I can replicate and get back to you. Apologies for the inconvenience!

**Comment by onehundredfeet** [comment]
Never mind.  It was the fact that I was using the raw repo and not the nightly.  Ignore this one.

**Comment by RobertBorghese** [comment]
You're all good! Please don't hesitate if you find anything else! 😁
